# Site settings
title: PHP Image Manipulation
email: me@cameronhurd.com
description: >
    An introduction to, and delineation between different methods of
    manipulating images in php.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cameronhurd.com" # the base hostname & protocol for your site
twitter_username: cameronhurd
github_username:  cam5

permalink: none

# Build settings
markdown: kramdown

exclude: ['_site', '_includes/code', 'composer.json', 'composer.lock', 'vendor']

